config/routes.rb
CloudFunded::Application.routes.draw do

  namespace :open_graph do 
    resources :actions do
      collection do
        get :follow
      end
    end
  end

  # Static Pages
  match '/how-it-works' => 'static_pages#how_it_works', as: :how_it_works
  match '/apply-for-funding' => 'static_pages#apply_for_funding', as: :apply_for_funding
  match '/about' => 'pages#show', id: 'about'

  namespace :projects do resources :roles end

  resources :comments

  mount Mercury::Engine => '/'

  resources :feedbacks, only: [:new, :create, :index]
  resources :pages, only: :show
  resources :articles, only: [:index, :show] do
    resources :comments
  end
  
  namespace :admin do
    resources :members, path_names: {edit: :chang3_that_sh1t}
    resources :feedbacks
    resources :transactions
    
    resources :pages do
      member { put :mercury_update }
      resources :attachments
    end
    
    resources :articles do
      member { 
        put :mercury_update 
        post :publish
      }
      resources :attachments
    end
    namespace :projects do
      resources :categories
    end
    resources :projects
    resources :test
  end

  resource :my_account, as: 'account', only: [:show, :edit, :update], controller: 'accounts' do
    member do 
      put :send_reset_password_instructions, as: :send_reset_password_instructions
      get :dwolla_auth_failure
    end
    resources :funds, path_names: {:new => 'add'}, controller: 'members/transactions'
  end
  
  resources :profiles
  resource :profile, path_names: {edit: :settings}
    
  namespace :projects do
    resources :categories
  end
  
  #  index
  #  new
  #  edit
  #  create
  #  show:    /projects/google
  #  update:  post a form to make a change to a resource
  #  delete

  resources :projects, path_names: {edit: :settings, :new => :fund_yours} do
    member do 
      put :mercury_update
      get :sharing
    end
    resources :admins, controller: 'projects/admins'
    resource :facebook_action
    resources :attachments, controller: 'admin/attachments'
    resource :my_pledge, controller: :pledges
    resources :pledges
    resources :team, as: :roles, controller: 'projects/roles' do
      member {get :confirm}
    end
    resources :updates, controller: 'projects/articles', path_names: {:new => :new, :edit => :edit} do
      member { 
        post :publish 
        put :mercury_update
      }
    end
    resources :transactions, controller: 'projects/transactions', path_names: {
      :new => :new, :edit => :edit
    }
    resources :perks, controller: 'projects/perks' do
      collection do
        post :sort
      end
    end
  end
  
  match '/members/auth/dwolla/callback' => 'accounts#dwolla_auth_failure' , constraints: {query_string: "access_denied&error_description=The+user+denied+the+request."}
    
  devise_for :members, controllers: {
    omniauth_callbacks: 'members/omniauth_callbacks',
    registrations: 'members/registrations',
    sessions: 'members/sessions',
    confirmations: 'members/confirmations'
  }
  
  match '/blog' => 'articles#index', as: :blog
  match '/blog/:id' => 'articles#show', as: :blog_post
  match '/admin' => 'admin/controls#index'
  match '/feedback' => 'feedbacks#new', as: :submit_feedback
  match '/feedback_received' => 'feedbacks#index', as: :feedback_received
  match '/my_projects' => 'projects#index', defaults: {show: "mine"}, as: :my_projects
  match '/member_search(.:format)' => 'accounts#search', as: :member_search
  
  match '/get_funded(/:id)' => 'projects/wizard#show', as: :get_funded, via: 'get'
  match '/get_funded(/:id)' => 'projects/wizard#update', via: 'put'
  
  match '/projects/:project_id/wizard(/:id)' => 'projects/wizard#show', as: :project_wizard, via: 'get'
  match '/projects/:project_id/wizard(/:id)' => 'projects/wizard#update', via: 'put'
  
  # resource :get_funded, controller: 'projects/wizard', as: :get_funded
  
  as :member do
    get '/my_account/change_password' => 'members/registrations#edit',  as: :change_password
  end
  
  match '/:id/widget' => 'projects#show', as: :project_widget, via: 'get', defaults: {display: "widget"}
  
  # match '/projects/:project_id/my_pledge/edit' => 'pledges#edit', as: :edit_my_pledge
  # match '/projects/:project_id/my_pledge' => 'pledges#show', as: :my_pledge
  match '/:id/comments' => 'projects#show', as: :project, defaults: {show: 'comments'}, via: 'get'
  match '/:id/team' => 'projects#show', as: :project, defaults: {show: 'team'}, via: 'get'
  match '/:id/updates' => 'projects#show', as: :project, defaults: {show: 'updates'}, via: 'get'
  match '/:id/pledges' => 'projects#show', as: :project, defaults: {show: 'pledges'}, via: 'get'
  match '/:id/info' => 'projects#show', as: :project, defaults: {show: 'info'}, via: 'get'
  match '/:id(.:format)' => 'projects#show', as: :project, :constraints => { :format => /(json|html)/ }, via: 'get'
  match '/:id(.:format)' => 'projects#update', as: :project, :constraints => { :format => /(json|html)/ }, via: 'post'

  match '/:project_id/pledge(/:id)' => 'projects/pledge_wizard#show', as: :new_project_pledge, via: 'get'
  match '/:project_id/pledge(/:id)' => 'projects/pledge_wizard#update', via: 'put'
  match '/:project_id/my_pledge(.:format)' => 'pledges#show', via: 'get', as: :project_my_pledge

  match '/projects/:project_id/perks/:id(.:format)' => 'projects/perks#update', via: :post

  root to: 'projects#index'
end

app/views/admin/pages/_form.html.haml
= form_for [:admin, @page] do |f|
  -if @page.errors.any?
    #error_explanation
      %h2= "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      %ul
        - @page.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :slug, "Url for page"
    = f.text_field :slug
  .field
    = f.label :description, 'Abstract for FB sharing'
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/admin/pages/edit.html.haml
%h1 Editing page

= render 'form'

= link_to 'Show', @page
\|
= link_to 'Edit Page Text', "/editor" + admin_page_path(@page)
\|
= link_to 'Back to page listing', admin_pages_path

app/views/admin/pages/index.html.haml
%h1 Listing pages

= link_to 'New Page', new_admin_page_path

%table
  %tr
    %th Title
    %th Description
    %th
    %th
    %th
    %th

  - @pages.each do |page|
    %tr
      %td= page.title
      %td= page.description
      %td= link_to 'Show', page
      %td= link_to 'Edit', '/editor' + admin_page_path(page)
      %td= link_to 'Page Properties', edit_admin_page_path(page)
      %td= link_to 'Destroy', admin_page_path(page), :confirm => 'Are you sure?', :method => :delete
%br

app/views/admin/pages/new.html.haml
%h1 New page

= render 'form'

= link_to 'Back', admin_pages_path

app/views/admin/pages/show.html.haml
.admin
  %p#notice= notice
  %span#edit_link= link_to('Edit Page', '/editor' + admin_page_path(@page)) + " |" unless request.path.match(/editor/)
  = link_to('Edit Attached Images', admin_page_attachments_path(@page)) + " |"
  = link_to('Go To Page List', admin_pages_path)

  .page#page_container.mercury_container{data: {'save-url' => mercury_update_admin_page_path(@page)}}
    %h1#page_title{mercury_full}= @page.title
    .body#page_body{mercury_full}!= @page.body
    %hr/
    Description / Abstract (one line)
    .description#page_description{mercury_full}!= @page.description

= render partial: 'shared/mercury_includes' if can? :edit, @page