config/routes.rb
CloudFunded::Application.routes.draw do

  namespace :open_graph do 
    resources :actions do
      collection do
        get :follow
      end
    end
  end

  # Static Pages
  match '/how-it-works' => 'static_pages#how_it_works', as: :how_it_works
  match '/apply-for-funding' => 'static_pages#apply_for_funding', as: :apply_for_funding
  match '/about' => 'pages#show', id: 'about'

  namespace :projects do resources :roles end

  resources :comments

  mount Mercury::Engine => '/'

  resources :feedbacks, only: [:new, :create, :index]
  resources :pages, only: :show
  resources :articles, only: [:index, :show] do
    resources :comments
  end
  
  namespace :admin do
    resources :members, path_names: {edit: :chang3_that_sh1t}
    resources :feedbacks
    resources :transactions
    
    resources :pages do
      member { put :mercury_update }
      resources :attachments
    end
    
    resources :articles do
      member { 
        put :mercury_update 
        post :publish
      }
      resources :attachments
    end
    namespace :projects do
      resources :categories
    end
    resources :projects
    resources :test
  end

  resource :my_account, as: 'account', only: [:show, :edit, :update], controller: 'accounts' do
    member do 
      put :send_reset_password_instructions, as: :send_reset_password_instructions
      get :dwolla_auth_failure
    end
    resources :funds, path_names: {:new => 'add'}, controller: 'members/transactions'
  end
  
  resources :profiles
  resource :profile, path_names: {edit: :settings}
    
  namespace :projects do
    resources :categories
  end
  
  #  index
  #  new
  #  edit
  #  create
  #  show:    /projects/google
  #  update:  post a form to make a change to a resource
  #  delete

  resources :projects, path_names: {edit: :settings, :new => :fund_yours} do
    member do 
      put :mercury_update
      get :sharing
    end
    resources :admins, controller: 'projects/admins'
    resource :facebook_action
    resources :attachments, controller: 'admin/attachments'
    resource :my_pledge, controller: :pledges
    resources :pledges
    resources :team, as: :roles, controller: 'projects/roles' do
      member {get :confirm}
    end
    resources :updates, controller: 'projects/articles', path_names: {:new => :new, :edit => :edit} do
      member { 
        post :publish 
        put :mercury_update
      }
    end
    resources :transactions, controller: 'projects/transactions', path_names: {
      :new => :new, :edit => :edit
    }
    resources :perks, controller: 'projects/perks' do
      collection do
        post :sort
      end
    end
  end
  
  match '/members/auth/dwolla/callback' => 'accounts#dwolla_auth_failure' , constraints: {query_string: "access_denied&error_description=The+user+denied+the+request."}
    
  devise_for :members, controllers: {
    omniauth_callbacks: 'members/omniauth_callbacks',
    registrations: 'members/registrations',
    sessions: 'members/sessions',
    confirmations: 'members/confirmations'
  }
  
  match '/blog' => 'articles#index', as: :blog
  match '/blog/:id' => 'articles#show', as: :blog_post
  match '/admin' => 'admin/controls#index'
  match '/feedback' => 'feedbacks#new', as: :submit_feedback
  match '/feedback_received' => 'feedbacks#index', as: :feedback_received
  match '/my_projects' => 'projects#index', defaults: {show: "mine"}, as: :my_projects
  match '/member_search(.:format)' => 'accounts#search', as: :member_search
  
  match '/get_funded(/:id)' => 'projects/wizard#show', as: :get_funded, via: 'get'
  match '/get_funded(/:id)' => 'projects/wizard#update', via: 'put'
  
  match '/projects/:project_id/wizard(/:id)' => 'projects/wizard#show', as: :project_wizard, via: 'get'
  match '/projects/:project_id/wizard(/:id)' => 'projects/wizard#update', via: 'put'
  
  # resource :get_funded, controller: 'projects/wizard', as: :get_funded
  
  as :member do
    get '/my_account/change_password' => 'members/registrations#edit',  as: :change_password
  end
  
  match '/:id/widget' => 'projects#show', as: :project_widget, via: 'get', defaults: {display: "widget"}
  
  # match '/projects/:project_id/my_pledge/edit' => 'pledges#edit', as: :edit_my_pledge
  # match '/projects/:project_id/my_pledge' => 'pledges#show', as: :my_pledge
  match '/:id/comments' => 'projects#show', as: :project, defaults: {show: 'comments'}, via: 'get'
  match '/:id/team' => 'projects#show', as: :project, defaults: {show: 'team'}, via: 'get'
  match '/:id/updates' => 'projects#show', as: :project, defaults: {show: 'updates'}, via: 'get'
  match '/:id/pledges' => 'projects#show', as: :project, defaults: {show: 'pledges'}, via: 'get'
  match '/:id/info' => 'projects#show', as: :project, defaults: {show: 'info'}, via: 'get'
  match '/:id(.:format)' => 'projects#show', as: :project, :constraints => { :format => /(json|html)/ }, via: 'get'
  match '/:id(.:format)' => 'projects#update', as: :project, :constraints => { :format => /(json|html)/ }, via: 'post'

  match '/:project_id/pledge(/:id)' => 'projects/pledge_wizard#show', as: :new_project_pledge, via: 'get'
  match '/:project_id/pledge(/:id)' => 'projects/pledge_wizard#update', via: 'put'
  match '/:project_id/my_pledge(.:format)' => 'pledges#show', via: 'get', as: :project_my_pledge

  match '/projects/:project_id/perks/:id(.:format)' => 'projects/perks#update', via: :post

  root to: 'projects#index'
end

app/controllers/admin/projects/categories_controller.rb
class Admin::Projects::CategoriesController < ApplicationController
  before_filter :authenticate_admin
  # GET /projects_categories
  # GET /projects_categories.xml
  def index
    @projects_categories = Projects::Category.all
    respond_with(@projects_categories) do |format|
      format.html {
        render layout: 'admin'
      }
    end
  end

  # GET /projects_categories/1
  # GET /projects_categories/1.xml
  def show
    @category = Projects::Category.find(params[:id])
    respond_with(@category)
  end

  # GET /projects_categories/new
  # GET /projects_categories/new.xml
  def new
    @category = Projects::Category.new
    respond_with(@category)
  end

  # GET /projects_categories/1/edit
  def edit
    @category = Projects::Category.find(params[:id])
  end

  # POST /projects_categories
  # POST /projects_categories.xml
  def create
    @category = Projects::Category.new(params[:category])
    @category.save
    respond_with(@category) do |format|
      format.html {
        if @category.persisted?
          redirect_to admin_projects_categories_path
        else
          render action: :new
        end
      }
    end
  end

  # PUT /projects_categories/1
  # PUT /projects_categories/1.xml
  def update
    @category = Projects::Category.find(params[:id])
    @category.update_attributes(params[:category])
    respond_with(@category) do |format|
      format.html {
        if @category.valid?
          redirect_to admin_projects_categories_path
        else
          render action: :edit
        end
      }
    end
  end

  # DELETE /projects_categories/1
  # DELETE /projects_categories/1.xml
  def destroy
    @category = Projects::Category.find(params[:id])
    @category.destroy
    respond_with(@category) do |format|
      format.html {
        redirect_to admin_projects_categories_path
      }
    end
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  before_filter :authenticate_admin!
  def index
    @projects = Project.all
    respond_with @projects do |format|
      format.html {
        render layout: 'admin'
      }
    end
  end
  
  def update
    @project = Project.find(params[:id])
    @project.update_attributes params[:project]
    respond_with(@project) do |format|
      format.html {
        redirect_to admin_projects_path
      }
    end
  end
  
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    respond_with(@project) do |format|
      format.html {
        redirect_to admin_projects_path
      }
    end
  end
  
  def authenticate_admin!
    authenticate_member!
    authorize! :manage, Project
  end
end

app/controllers/projects/admins_controller.rb
class Projects::AdminsController < ApplicationController
  before_filter :authenticate_member!, :load_project
  respond_to :js, :html
  # layout 'edit_projects'
  
  def index
    @admins = @project.admins
    authorize! :edit, @project
  end
  
  def create
    authorize! :edit, @project
    @admin = Member.find(params[:member_id])
    @project.admins << @admin
    MemberMailer.new_project_admin(@admin, @project).deliver!
  end
  
  def destroy
    authorize! :edit, @project
    @admin = Member.find(params[:id])
    @project.admins.delete(@admin)
  end
  
  def load_project
    @project = Project.find(params[:project_id])
  end
end

app/controllers/projects/articles_controller.rb
class Projects::ArticlesController < ApplicationController
  respond_to :html, :js, :json
  before_filter :load_project, :authenticate_member!
  
  def index
    @articles = @project.articles.accessible_by(current_ability)
    respond_with @project, @articles
  end
  
  def create
    authorize! :edit, @project
    @article = Article.new
    @article.project = @project
    @article.author = current_member
    @article.save
    respond_with @project, @article do |format|
      format.html {
        redirect_to '/editor' + project_path(@project) + '/updates'
      }
    end
  end
  
  def show
    @article = @project.articles.find(params[:id])
    authorize! :read, @article
    @title = @article.title
    respond_with @project, @article
  end
  
  def publish
    @article = @project.articles.find(params[:id])
    authorize! :edit, @article
    @article.publish! unless @article.published?
    respond_with @project, @article do |format|
      format.json {
        render text: ""
      }
    end
  end
  
  def destroy
    @article = @project.articles.find(params[:id])
    authorize! :destroy, @article
    @article.destroy
    respond_with @project, @article
  end
  
  def load_project
    @project = Project.find params[:project_id]
  end
end

app/controllers/projects/categories_controller.rb
class Projects::CategoriesController < ApplicationController
  def index
    @categories = Projects::Category.all
    respond_with @categories
  end
  
  def show
    @category = Projects::Category.find(params[:id])
    respond_with @category
  end
end

app/controllers/projects/perks_controller.rb
class Projects::PerksController < ApplicationController
  respond_to :js, :json, :html
  before_filter :load_project
  
  def index
    authorize! :edit, @project
    @perks = @project.perks
    
     respond_with @project, @perk do |format|
      format.html {
        render layout: 'edit_projects'
      }
    end
  end
  
  def edit
    @perk = @project.perks.find params[:id]
    authorize! :edit, @perk
    respond_with @project, @perk
  end
  
  def sort
    authorize! :edit, @project
    params[:order].each_with_index do |id, index|
      perk = @project.perks.select{|t| t.id==id.to_i}.first
      perk.sort_order = index
      perk.save! validate: false
    end
    render text: ''
  end
  
  def create
    @perk = @project.perks.build params[:perk]
    authorize! :edit, @perk
    authorize! :create, @perk
    @perk.save
    respond_with @project, @perk
  end
  
  def show
    @perk = @project.perks.find(params[:id])
    authorize! :edit, @perk
  end
  
  def update
    @perk = @project.perks.find(params[:id])
    authorize! :edit, @perk
    @perk.update_attributes params[:perk]
    unless @perk.valid?
      puts @perk.errors.inspect
    end
    respond_with @project, @perk do |format|
      format.html {
        redirect_to project_perks_path(@project)
      }
      format.json {
        render json: @perk.as_json
      }
    end
  end
  
  def destroy
    @perk = @project.perks.find(params[:id])
    authorize! :destroy, @perk
    @perk.destroy

    respond_with @project, @perk do |format|
      format.html {
        redirect_to project_perks_path(@project)
      }
      format.json {
        render json: @perk.as_json
      }
    end
  end
  
  def load_project
    authenticate_member!
    @project = Project.find(params[:project_id])
  end
end

app/controllers/projects/pledge_wizard_controller.rb
class Projects::PledgeWizardController < ApplicationController
  include Wicked::Wizard
  layout 'pledge_wizard'
  
  steps :amount, :payment_method, :dwolla, :cc, :share

  before_filter :authenticate_member!, :load_project

  def finish_wizard_path
    project_my_pledge_path(@project)
  end
      
  def show
    if current_member.funded?(@project)
      redirect_to project_my_pledge_path(@project)
    else
      puts step.inspect + "\n*" * 10
      case step
      when :amount
        @breadcrumbs = [['Amount + Perks', :amount]]
      when :payment_method
        @breadcrumbs = [['Amount + Perks', :amount], ['Payment Method', :payment_method]]
      when :dwolla
        @breadcrumbs = [['Amount + Perks', :amount], ['Payment Method', :payment_method], ['Pay with Dwolla', :dwolla]]
        if current_member.linked_to_dwolla?
          @funding_sources = Dwolla::User.me(current_member.dwolla_auth_token).funding_sources.select{|f|
            f.verified
          }.map{|f|
            [f.name, f.id]
          }
          @funding_sources.unshift ['Dwolla Account', '']
        end
      when :cc
        @breadcrumbs = [['Amount + Perks', :amount], ['Payment Method', :payment_method], ['Pay with Credit Card', :cc]]
      end
    
      authorize! :edit, @pledge
      render_wizard
    end
  end
  
  def update
    authorize! :edit, @pledge
    if params[:pledge]
      @pledge.update_attributes params[:pledge]
    end
    if respond_to?("submit_#{step}")
      send "submit_#{step}"
    else
      render_wizard(@pledge)
    end
  end
  
  def submit_amount
    render_wizard(@pledge)
  end
  
  def submit_payment_method
    unless @pledge.valid?
      render_wizard(@pledge)
    else
      redirect_to wizard_path(@pledge.payment_method)
    end
  end
  
  def submit_cc
    begin
      token = params[:stripe_token]
      raise "blahblah" if token.blank?
      @charge = Stripe::Charge.create(
        :amount => @pledge.amount_cents, # amount in cents, again
        :currency => "usd",
        :card => token,
        :description => "CloudFunded pledge to #{@project.name}"
      )
      @stripe_transaction = StripeTransaction.from_stripe_charge(@charge)
      @stripe_transaction.member = current_member
      @stripe_transaction.pledge = @pledge
      @stripe_transaction.save!
      if @pledge.valid?
        @pledge.pay_by_cc!
      end
      render_wizard(@pledge)
    rescue Stripe::CardError => e
      flash[:alert] = e.message
      # puts e.inspect
      render :cc
    rescue Exception => e
      flash[:alert] = e.message
      # puts e.inspect
      render :cc
    end
  end
  
  def load_project
    @project = params[:project_id] ? 
                  Project.find(params[:project_id]) : 
                  current_member.project_application
    pledges = Pledge.where(project_id: @project.id, investor_id: current_member.id)
    @pledge = pledges.empty? ? pledges.create! : pledges.first
  end
  
  # def redirect_as_needed
  #   unless params[:id]
  #     if step != WORKFLOW_STATE_WIZARD_STEP[@pledge.workflow_state]
  #       the_correct_step = WORKFLOW_STATE_WIZARD_STEP[@pledge.workflow_state]
  #       if the_correct_step == :pledge
  #         redirect_to new_project_pledge_path(@project)
  #       else
  #         redirect_to new_project_pledge_path(@project, the_correct_step)
  #       end
  #     end
  #   end
  # end
  
  WORKFLOW_STATE_WIZARD_STEP = {
    'new' => :amount,
    'not_pledged' => :amount,
    'choose_payment_method' => :payment_method,
    'pay_by_cc' => :pay_by_cc,
    'payment_received' => :share
  }
end

app/controllers/projects/roles_controller.rb
class Projects::RolesController < ApplicationController
  respond_to :js
  before_filter :authenticate_member!, :load_project
  
  def new
    authorize! :edit, @project
    @role = @project.roles.build
    @role.invited_by = current_member
    respond_with @project, @role do |format|
      format.html {
        render layout: 'edit_projects'
      }
    end
  end
  
  def index
    authorize! :edit, @project
    @roles = @project.roles
    respond_with @project, @role do |format|
      format.html {
        render layout: 'edit_projects'
      }
    end
  end
  
  def create
    authorize! :edit, @project
    @role = @project.roles.build(params[:role])
    if @role.member
      @role.email_address = @role.member.email
    end
    @role.invited_by = current_member
    @member = Member.where(email: @role.email_address).first
    if @member
      @role.member = @member
    end
    @role.save
    respond_with @project, @role
  end
  
  def edit
    @role = @project.roles.find(params[:id])
    authorize! :edit, @role
    respond_with(@role,@project)
  end

  def update
    @role = @project.roles.find(params[:id])
    authorize! :edit, @role
    @role.update_attributes params[:role]
    respond_with(@role,@project)
  end
  
  def confirm
    @role = @project.roles.find(params[:id])
    authorize! :confirm, @role
    @role.confirm!
    respond_with @project, @role
  end
  
  def destroy
    @role = @project.roles.find(params[:id])
    authorize! :destroy, @role
    @role.destroy
    respond_with @project, @role
  end
  
  def load_project
    @project = Project.find(params[:project_id])
  end
end

app/controllers/projects/transactions_controller.rb
class Projects::TransactionsController < ApplicationController
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects/categories_helper.rb
module Projects::CategoriesHelper
end

app/helpers/projects/roles_helper.rb
module Projects::RolesHelper
end

app/views/projects/roles/_confirmed.html.haml
.dialog
  %h3 Confirmed.
  %p Then it's true!  You are truly the #{@role.name} at #{@role.project.name}.  Welcome aboard!

app/views/projects/roles/_created.html.haml
.dialog
  %h3 New Team Member Added.
  %p An email was sent to #{@role.email_address} asking them to confirm.

app/views/projects/roles/_destroyed.html.haml
.dialog
  %h3 Removed
  %p #{@role.email_address} / #{@role.name} was removed from #{@role.project.name}.

app/views/projects/roles/_edit.html.erb
<div class="modal hide" id="edit_role">
  <%= form_for @role, as: :role, url: project_role_path(@project, @role), remote: true do |f| -%>
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">×</button>
      <h3>Edit Team Membership</h3>
    </div>
    <div class="modal-body">
      <div class="control-group">
        <%= f.label :name, "Role / Title", :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :name, :class => 'input-xlarge' %>
          <p class="help-block">This person's Job Title</p>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :tagline, "Tagline", :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :tagline, :class => 'input-xlarge' %>
          <p class="help-block">One-liner about this person's role</p>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal">Cancel</a>
      <%= f.submit "Save", :disable_with => 'Saving...', :class => "btn btn-primary" %>
    </div>
  <% end -%>
</div>

app/views/projects/roles/_new.html.erb
<div class="modal hide" id="new_role">
  <%= form_for @role, as: :role, url: project_roles_path(@project), remote: true do |f| -%>
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">×</button>
      <h3>Add a Team Member</h3>
    </div>
    <div class="modal-body">
      <div class="control-group" id="email_address_controls">
        <%= f.hidden_field :member_id %>
        <%= f.label :email_address, "Email or Name", :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :email_address, :class => 'input-xlarge', data: {provide: :typeahead} %>
          <p class="help-block">Name or Email.  If no one is found, provide an email and we'll invite them to join.</p>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :name, "Role / Title", :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :name, :class => 'input-xlarge' %>
          <p class="help-block">This person's Job Title</p>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :tagline, "Tagline", :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :tagline, :class => 'input-xlarge' %>
          <p class="help-block">One-liner about this person's role</p>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal">Cancel</a>
      <%= f.submit "Save", :disable_with => 'Saving...', :class => "btn btn-primary" %>
    </div>
  <% end -%>
</div>

app/views/projects/roles/_role.html.haml
.role.row[role]
  .span1
    - if role.member && role.member.profile_pic
      = link_to profile_path(role.member) do
        = image_tag role.member.profile_pic
  .span4
    - if can? :edit, role
      = link_to edit_project_role_path(role.project, role), rel: 'tooltip', title: 'Edit This Role', data: {remote: true} do
        %i.icon.icon-cog
    - if can? :destroy, role
      = link_to project_role_path(role.project, role), class: 'tippy', rel: 'tooltip', title: 'Remove This Role', method: :delete, data: {confirm: 'You really want to remove this team member?', remote: true} do
        %i.icon.icon-remove
    .person
      - if role.member
        = link_to profile_path(role.member) do
          %span.name= role.member.full_name
      - else
        %span= role.email_address
      %span.role_name / #{role.name}
    .tagline= role.tagline
    - if can? :edit, role
      .status
        Status: #{role.workflow_state.titleize}
        - if can?(:confirm, role) && role.unconfirmed?
          = link_to 'Confirm', confirm_project_role_path(role.project, role), data: {confirm: 'This is to confirm that you are on this team.', remote: true}
  %hr/

app/views/projects/roles/_updated.html.haml
.dialog
  %h3 Snap!
  %p The team member was updated.

app/views/projects/roles/confirm.js.erb
$('#projects_role_<%= @role.id %>').replaceWith('<%= escape_javascript render @role %>');
bootbox.alert('<%= escape_javascript render(partial: 'confirmed') %>')

app/views/projects/roles/create.js.erb
$('#new_role').modal('hide');
$('#team').append('<%= escape_javascript render @role %>');
bootbox.alert('<%= escape_javascript render(partial: 'created') %>')

app/views/projects/roles/destroy.js.erb
$('#projects_role_<%= @role.id %>').remove();
bootbox.alert('<%= escape_javascript render(partial: 'destroyed') %>')

app/views/projects/roles/index.html.haml
%h1 Team Members

#team.tab-pane.shadow
  = link_to "Add A Team Member", new_project_role_path(@project, format: :js), data: {remote: true}
  %br/
  %br/
  %br/
  = render @roles

app/views/projects/roles/new.html.haml
%h2 Add a Team Member
= render partial: 'new'

app/views/projects/roles/update.js.erb
$('#edit_role').modal('hide');
$('#projects_role_<%= @role.id %>').replaceWith('<%= escape_javascript render @role %>');
bootbox.alert('<%= escape_javascript render(partial: 'updated') %>');