config/routes.rb
CloudFunded::Application.routes.draw do

  namespace :open_graph do 
    resources :actions do
      collection do
        get :follow
      end
    end
  end

  # Static Pages
  match '/how-it-works' => 'static_pages#how_it_works', as: :how_it_works
  match '/apply-for-funding' => 'static_pages#apply_for_funding', as: :apply_for_funding
  match '/about' => 'pages#show', id: 'about'

  namespace :projects do resources :roles end

  resources :comments

  mount Mercury::Engine => '/'

  resources :feedbacks, only: [:new, :create, :index]
  resources :pages, only: :show
  resources :articles, only: [:index, :show] do
    resources :comments
  end
  
  namespace :admin do
    resources :members, path_names: {edit: :chang3_that_sh1t}
    resources :feedbacks
    resources :transactions
    
    resources :pages do
      member { put :mercury_update }
      resources :attachments
    end
    
    resources :articles do
      member { 
        put :mercury_update 
        post :publish
      }
      resources :attachments
    end
    namespace :projects do
      resources :categories
    end
    resources :projects
    resources :test
  end

  resource :my_account, as: 'account', only: [:show, :edit, :update], controller: 'accounts' do
    member do 
      put :send_reset_password_instructions, as: :send_reset_password_instructions
      get :dwolla_auth_failure
    end
    resources :funds, path_names: {:new => 'add'}, controller: 'members/transactions'
  end
  
  resources :profiles
  resource :profile, path_names: {edit: :settings}
    
  namespace :projects do
    resources :categories
  end
  
  #  index
  #  new
  #  edit
  #  create
  #  show:    /projects/google
  #  update:  post a form to make a change to a resource
  #  delete

  resources :projects, path_names: {edit: :settings, :new => :fund_yours} do
    member do 
      put :mercury_update
      get :sharing
    end
    resources :admins, controller: 'projects/admins'
    resource :facebook_action
    resources :attachments, controller: 'admin/attachments'
    resource :my_pledge, controller: :pledges
    resources :pledges
    resources :team, as: :roles, controller: 'projects/roles' do
      member {get :confirm}
    end
    resources :updates, controller: 'projects/articles', path_names: {:new => :new, :edit => :edit} do
      member { 
        post :publish 
        put :mercury_update
      }
    end
    resources :transactions, controller: 'projects/transactions', path_names: {
      :new => :new, :edit => :edit
    }
    resources :perks, controller: 'projects/perks' do
      collection do
        post :sort
      end
    end
  end
  
  match '/members/auth/dwolla/callback' => 'accounts#dwolla_auth_failure' , constraints: {query_string: "access_denied&error_description=The+user+denied+the+request."}
    
  devise_for :members, controllers: {
    omniauth_callbacks: 'members/omniauth_callbacks',
    registrations: 'members/registrations',
    sessions: 'members/sessions',
    confirmations: 'members/confirmations'
  }
  
  match '/blog' => 'articles#index', as: :blog
  match '/blog/:id' => 'articles#show', as: :blog_post
  match '/admin' => 'admin/controls#index'
  match '/feedback' => 'feedbacks#new', as: :submit_feedback
  match '/feedback_received' => 'feedbacks#index', as: :feedback_received
  match '/my_projects' => 'projects#index', defaults: {show: "mine"}, as: :my_projects
  match '/member_search(.:format)' => 'accounts#search', as: :member_search
  
  match '/get_funded(/:id)' => 'projects/wizard#show', as: :get_funded, via: 'get'
  match '/get_funded(/:id)' => 'projects/wizard#update', via: 'put'
  
  match '/projects/:project_id/wizard(/:id)' => 'projects/wizard#show', as: :project_wizard, via: 'get'
  match '/projects/:project_id/wizard(/:id)' => 'projects/wizard#update', via: 'put'
  
  # resource :get_funded, controller: 'projects/wizard', as: :get_funded
  
  as :member do
    get '/my_account/change_password' => 'members/registrations#edit',  as: :change_password
  end
  
  match '/:id/widget' => 'projects#show', as: :project_widget, via: 'get', defaults: {display: "widget"}
  
  # match '/projects/:project_id/my_pledge/edit' => 'pledges#edit', as: :edit_my_pledge
  # match '/projects/:project_id/my_pledge' => 'pledges#show', as: :my_pledge
  match '/:id/comments' => 'projects#show', as: :project, defaults: {show: 'comments'}, via: 'get'
  match '/:id/team' => 'projects#show', as: :project, defaults: {show: 'team'}, via: 'get'
  match '/:id/updates' => 'projects#show', as: :project, defaults: {show: 'updates'}, via: 'get'
  match '/:id/pledges' => 'projects#show', as: :project, defaults: {show: 'pledges'}, via: 'get'
  match '/:id/info' => 'projects#show', as: :project, defaults: {show: 'info'}, via: 'get'
  match '/:id(.:format)' => 'projects#show', as: :project, :constraints => { :format => /(json|html)/ }, via: 'get'
  match '/:id(.:format)' => 'projects#update', as: :project, :constraints => { :format => /(json|html)/ }, via: 'post'

  match '/:project_id/pledge(/:id)' => 'projects/pledge_wizard#show', as: :new_project_pledge, via: 'get'
  match '/:project_id/pledge(/:id)' => 'projects/pledge_wizard#update', via: 'put'
  match '/:project_id/my_pledge(.:format)' => 'pledges#show', via: 'get', as: :project_my_pledge

  match '/projects/:project_id/perks/:id(.:format)' => 'projects/perks#update', via: :post

  root to: 'projects#index'
end

app/views/shared/_admin_controls.html.haml
%li.nav-header Admin Controls
%li= link_to 'Members', admin_members_path
%li= link_to 'Pages', admin_pages_path
%li= link_to 'Projects', admin_projects_path
%li= link_to 'Feedback', admin_feedbacks_path
%li= link_to 'Blog Articles', admin_articles_path
%li= link_to 'Categories', admin_projects_categories_path
%li= link_to 'Transactions', admin_transactions_path
%li= link_to 'Sign Out', destroy_member_session_path, method: :delete

app/views/shared/_flash_message.html.haml
.span3.alert-message.fade.in{ "data-alert" => "alert", :class => twitterized_type(type) }
  %a.close{:href => "#", data: {dismiss: 'alert'}}
    %i.icon.icon-remove
  %p= message

app/views/shared/_footer.html.erb
<div class="row">
  <div class="offset1 span2">
    <a href="https://twitter.com/cloudfunded" class="twitter-follow-button" data-show-count="false">
      Follow @cloudfunded
    </a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>  
  </div>
  <div class="span6 fb-like" data-href="http://facebook.com/cloudfunded" data-send="false" data-width="450" data-show-faces="true"></div>
  <div class="span2">
    &copy; Cloudfunded 2012 &nbsp; &nbsp; &nbsp;
  </div>
</div>

app/views/shared/_footer.html.haml
.row
  .offset1.span2
    %a.twitter-follow-button{"data-show-count" => "true", :href => "https://twitter.com/cloudfunded"}
      Follow @cloudfunded
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  .span6.fb-like{"data-href" => "http://facebook.com/cloudfunded", "data-send" => "false", "data-show-faces" => "true", "data-width" => "450"}
  .span2
    © Cloudfunded 2012      
  .span1
    Got feedback? 
    %a= link_to 'Let us know', submit_feedback_path(about_page: request.path)

app/views/shared/_header_nav.html.haml
.navbar.navbar-fixed-top.header
  .navbar-inner
    .container
      %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .row
        .span3
          %a.brand{href: root_path} &nbsp;
        .span6.offset3
          .container.nav-collapse
            %ul.nav.nav-pills
              -# %li.dropdown.project_categories
              -#   %a.dropdown-toggle{href: '#', data: {toggle: :dropdown}}
              -#     Invest
              -#     %b.caret
              -#   %ul.dropdown-menu
              -#     %li= link_to 'All Companies', projects_path
              -#     - Projects::Category.all.each do |category|
              -#       %li= link_to category.name, projects_category_path(category)
              
              %li= link_to 'Get Funded', get_funded_path
              %li= link_to 'Read the Blog', blog_path
              %li= link_to 'Learn More', '/about'
               

              - unless member_signed_in?
                %li= link_to 'Sign In', new_member_session_path
                %li.fblogin
                  = link_to member_omniauth_authorize_path(:facebook) do
                    = image_tag 'signin_facebook.png'
              - else
                %li= link_to 'My Account', account_path
                - if current_member.admin
                  %li.dropdown
                    %a.droptown-toggle{href: '#', data: {toggle: :dropdown}}
                      %b.caret
                    %ul.dropdown-menu
                      = render partial: 'shared/admin_controls'
                    
              -# %li.dropdown

app/views/shared/_mercury_includes.html.haml
- if mercury_editor_open?
  = content_for :javascripts do
    = stylesheet_link_tag 'mercury_includes'
    = javascript_include_tag 'mercury_includes'

app/views/shared/_open_graph_data.html.haml
%meta#og_namespace{property: 'og_namespace', content: ENV['OPENGRAPH_NAMESPACE']}
%meta{property: 'fb:app_id', content: facebook_app_id}

- if content_for?(:open_graph)
  = yield :open_graph
- else
  %link{rel: 'image_src', href: '/assets/info.png'}
  %meta{property: 'og:type', content: 'website'}
  %meta{property: 'og:title', content: 'CloudFunded'}
  %meta{property: 'og:image', content: '/assets/info.png'}
  %meta{property: 'og:description', content: 'Cloud Funded... Fund You Too.'}

app/views/shared/archived_footer.html.erb
<div class="row">
  <div class="offset1 span2">
    <a href="https://twitter.com/cloudfunded" class="twitter-follow-button" data-show-count="false">
      Follow @cloudfunded
    </a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>  
  </div>
  <div class="span6 fb-like" data-href="http://facebook.com/cloudfunded" data-send="false" data-width="450" data-show-faces="true"></div>
  <div class="span2">
    &copy; Cloudfunded 2012 &nbsp; &nbsp; &nbsp;
  </div>
</div>