config/routes.rb
CloudFunded::Application.routes.draw do

  namespace :open_graph do 
    resources :actions do
      collection do
        get :follow
      end
    end
  end

  # Static Pages
  match '/how-it-works' => 'static_pages#how_it_works', as: :how_it_works
  match '/apply-for-funding' => 'static_pages#apply_for_funding', as: :apply_for_funding
  match '/about' => 'pages#show', id: 'about'

  namespace :projects do resources :roles end

  resources :comments

  mount Mercury::Engine => '/'

  resources :feedbacks, only: [:new, :create, :index]
  resources :pages, only: :show
  resources :articles, only: [:index, :show] do
    resources :comments
  end
  
  namespace :admin do
    resources :members, path_names: {edit: :chang3_that_sh1t}
    resources :feedbacks
    resources :transactions
    
    resources :pages do
      member { put :mercury_update }
      resources :attachments
    end
    
    resources :articles do
      member { 
        put :mercury_update 
        post :publish
      }
      resources :attachments
    end
    namespace :projects do
      resources :categories
    end
    resources :projects
    resources :test
  end

  resource :my_account, as: 'account', only: [:show, :edit, :update], controller: 'accounts' do
    member do 
      put :send_reset_password_instructions, as: :send_reset_password_instructions
      get :dwolla_auth_failure
    end
    resources :funds, path_names: {:new => 'add'}, controller: 'members/transactions'
  end
  
  resources :profiles
  resource :profile, path_names: {edit: :settings}
    
  namespace :projects do
    resources :categories
  end
  
  #  index
  #  new
  #  edit
  #  create
  #  show:    /projects/google
  #  update:  post a form to make a change to a resource
  #  delete

  resources :projects, path_names: {edit: :settings, :new => :fund_yours} do
    member do 
      put :mercury_update
      get :sharing
    end
    resources :admins, controller: 'projects/admins'
    resource :facebook_action
    resources :attachments, controller: 'admin/attachments'
    resource :my_pledge, controller: :pledges
    resources :pledges
    resources :team, as: :roles, controller: 'projects/roles' do
      member {get :confirm}
    end
    resources :updates, controller: 'projects/articles', path_names: {:new => :new, :edit => :edit} do
      member { 
        post :publish 
        put :mercury_update
      }
    end
    resources :transactions, controller: 'projects/transactions', path_names: {
      :new => :new, :edit => :edit
    }
    resources :perks, controller: 'projects/perks' do
      collection do
        post :sort
      end
    end
  end
  
  match '/members/auth/dwolla/callback' => 'accounts#dwolla_auth_failure' , constraints: {query_string: "access_denied&error_description=The+user+denied+the+request."}
    
  devise_for :members, controllers: {
    omniauth_callbacks: 'members/omniauth_callbacks',
    registrations: 'members/registrations',
    sessions: 'members/sessions',
    confirmations: 'members/confirmations'
  }
  
  match '/blog' => 'articles#index', as: :blog
  match '/blog/:id' => 'articles#show', as: :blog_post
  match '/admin' => 'admin/controls#index'
  match '/feedback' => 'feedbacks#new', as: :submit_feedback
  match '/feedback_received' => 'feedbacks#index', as: :feedback_received
  match '/my_projects' => 'projects#index', defaults: {show: "mine"}, as: :my_projects
  match '/member_search(.:format)' => 'accounts#search', as: :member_search
  
  match '/get_funded(/:id)' => 'projects/wizard#show', as: :get_funded, via: 'get'
  match '/get_funded(/:id)' => 'projects/wizard#update', via: 'put'
  
  match '/projects/:project_id/wizard(/:id)' => 'projects/wizard#show', as: :project_wizard, via: 'get'
  match '/projects/:project_id/wizard(/:id)' => 'projects/wizard#update', via: 'put'
  
  # resource :get_funded, controller: 'projects/wizard', as: :get_funded
  
  as :member do
    get '/my_account/change_password' => 'members/registrations#edit',  as: :change_password
  end
  
  match '/:id/widget' => 'projects#show', as: :project_widget, via: 'get', defaults: {display: "widget"}
  
  # match '/projects/:project_id/my_pledge/edit' => 'pledges#edit', as: :edit_my_pledge
  # match '/projects/:project_id/my_pledge' => 'pledges#show', as: :my_pledge
  match '/:id/comments' => 'projects#show', as: :project, defaults: {show: 'comments'}, via: 'get'
  match '/:id/team' => 'projects#show', as: :project, defaults: {show: 'team'}, via: 'get'
  match '/:id/updates' => 'projects#show', as: :project, defaults: {show: 'updates'}, via: 'get'
  match '/:id/pledges' => 'projects#show', as: :project, defaults: {show: 'pledges'}, via: 'get'
  match '/:id/info' => 'projects#show', as: :project, defaults: {show: 'info'}, via: 'get'
  match '/:id(.:format)' => 'projects#show', as: :project, :constraints => { :format => /(json|html)/ }, via: 'get'
  match '/:id(.:format)' => 'projects#update', as: :project, :constraints => { :format => /(json|html)/ }, via: 'post'

  match '/:project_id/pledge(/:id)' => 'projects/pledge_wizard#show', as: :new_project_pledge, via: 'get'
  match '/:project_id/pledge(/:id)' => 'projects/pledge_wizard#update', via: 'put'
  match '/:project_id/my_pledge(.:format)' => 'pledges#show', via: 'get', as: :project_my_pledge

  match '/projects/:project_id/perks/:id(.:format)' => 'projects/perks#update', via: :post

  root to: 'projects#index'
end

app/controllers/admin/projects/categories_controller.rb
class Admin::Projects::CategoriesController < ApplicationController
  before_filter :authenticate_admin
  # GET /projects_categories
  # GET /projects_categories.xml
  def index
    @projects_categories = Projects::Category.all
    respond_with(@projects_categories) do |format|
      format.html {
        render layout: 'admin'
      }
    end
  end

  # GET /projects_categories/1
  # GET /projects_categories/1.xml
  def show
    @category = Projects::Category.find(params[:id])
    respond_with(@category)
  end

  # GET /projects_categories/new
  # GET /projects_categories/new.xml
  def new
    @category = Projects::Category.new
    respond_with(@category)
  end

  # GET /projects_categories/1/edit
  def edit
    @category = Projects::Category.find(params[:id])
  end

  # POST /projects_categories
  # POST /projects_categories.xml
  def create
    @category = Projects::Category.new(params[:category])
    @category.save
    respond_with(@category) do |format|
      format.html {
        if @category.persisted?
          redirect_to admin_projects_categories_path
        else
          render action: :new
        end
      }
    end
  end

  # PUT /projects_categories/1
  # PUT /projects_categories/1.xml
  def update
    @category = Projects::Category.find(params[:id])
    @category.update_attributes(params[:category])
    respond_with(@category) do |format|
      format.html {
        if @category.valid?
          redirect_to admin_projects_categories_path
        else
          render action: :edit
        end
      }
    end
  end

  # DELETE /projects_categories/1
  # DELETE /projects_categories/1.xml
  def destroy
    @category = Projects::Category.find(params[:id])
    @category.destroy
    respond_with(@category) do |format|
      format.html {
        redirect_to admin_projects_categories_path
      }
    end
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  before_filter :authenticate_admin!
  def index
    @projects = Project.all
    respond_with @projects do |format|
      format.html {
        render layout: 'admin'
      }
    end
  end
  
  def update
    @project = Project.find(params[:id])
    @project.update_attributes params[:project]
    respond_with(@project) do |format|
      format.html {
        redirect_to admin_projects_path
      }
    end
  end
  
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    respond_with(@project) do |format|
      format.html {
        redirect_to admin_projects_path
      }
    end
  end
  
  def authenticate_admin!
    authenticate_member!
    authorize! :manage, Project
  end
end

app/controllers/projects/admins_controller.rb
class Projects::AdminsController < ApplicationController
  before_filter :authenticate_member!, :load_project
  respond_to :js, :html
  # layout 'edit_projects'
  
  def index
    @admins = @project.admins
    authorize! :edit, @project
  end
  
  def create
    authorize! :edit, @project
    @admin = Member.find(params[:member_id])
    @project.admins << @admin
    MemberMailer.new_project_admin(@admin, @project).deliver!
  end
  
  def destroy
    authorize! :edit, @project
    @admin = Member.find(params[:id])
    @project.admins.delete(@admin)
  end
  
  def load_project
    @project = Project.find(params[:project_id])
  end
end

app/controllers/projects/articles_controller.rb
class Projects::ArticlesController < ApplicationController
  respond_to :html, :js, :json
  before_filter :load_project, :authenticate_member!
  
  def index
    @articles = @project.articles.accessible_by(current_ability)
    respond_with @project, @articles
  end
  
  def create
    authorize! :edit, @project
    @article = Article.new
    @article.project = @project
    @article.author = current_member
    @article.save
    respond_with @project, @article do |format|
      format.html {
        redirect_to '/editor' + project_path(@project) + '/updates'
      }
    end
  end
  
  def show
    @article = @project.articles.find(params[:id])
    authorize! :read, @article
    @title = @article.title
    respond_with @project, @article
  end
  
  def publish
    @article = @project.articles.find(params[:id])
    authorize! :edit, @article
    @article.publish! unless @article.published?
    respond_with @project, @article do |format|
      format.json {
        render text: ""
      }
    end
  end
  
  def destroy
    @article = @project.articles.find(params[:id])
    authorize! :destroy, @article
    @article.destroy
    respond_with @project, @article
  end
  
  def load_project
    @project = Project.find params[:project_id]
  end
end

app/controllers/projects/categories_controller.rb
class Projects::CategoriesController < ApplicationController
  def index
    @categories = Projects::Category.all
    respond_with @categories
  end
  
  def show
    @category = Projects::Category.find(params[:id])
    respond_with @category
  end
end

app/controllers/projects/perks_controller.rb
class Projects::PerksController < ApplicationController
  respond_to :js, :json, :html
  before_filter :load_project
  
  def index
    authorize! :edit, @project
    @perks = @project.perks
    
     respond_with @project, @perk do |format|
      format.html {
        render layout: 'edit_projects'
      }
    end
  end
  
  def edit
    @perk = @project.perks.find params[:id]
    authorize! :edit, @perk
    respond_with @project, @perk
  end
  
  def sort
    authorize! :edit, @project
    params[:order].each_with_index do |id, index|
      perk = @project.perks.select{|t| t.id==id.to_i}.first
      perk.sort_order = index
      perk.save! validate: false
    end
    render text: ''
  end
  
  def create
    @perk = @project.perks.build params[:perk]
    authorize! :edit, @perk
    authorize! :create, @perk
    @perk.save
    respond_with @project, @perk
  end
  
  def show
    @perk = @project.perks.find(params[:id])
    authorize! :edit, @perk
  end
  
  def update
    @perk = @project.perks.find(params[:id])
    authorize! :edit, @perk
    @perk.update_attributes params[:perk]
    unless @perk.valid?
      puts @perk.errors.inspect
    end
    respond_with @project, @perk do |format|
      format.html {
        redirect_to project_perks_path(@project)
      }
      format.json {
        render json: @perk.as_json
      }
    end
  end
  
  def destroy
    @perk = @project.perks.find(params[:id])
    authorize! :destroy, @perk
    @perk.destroy

    respond_with @project, @perk do |format|
      format.html {
        redirect_to project_perks_path(@project)
      }
      format.json {
        render json: @perk.as_json
      }
    end
  end
  
  def load_project
    authenticate_member!
    @project = Project.find(params[:project_id])
  end
end

app/controllers/projects/pledge_wizard_controller.rb
class Projects::PledgeWizardController < ApplicationController
  include Wicked::Wizard
  layout 'pledge_wizard'
  
  steps :amount, :payment_method, :dwolla, :cc, :share

  before_filter :authenticate_member!, :load_project

  def finish_wizard_path
    project_my_pledge_path(@project)
  end
      
  def show
    if current_member.funded?(@project)
      redirect_to project_my_pledge_path(@project)
    else
      puts step.inspect + "\n*" * 10
      case step
      when :amount
        @breadcrumbs = [['Amount + Perks', :amount]]
      when :payment_method
        @breadcrumbs = [['Amount + Perks', :amount], ['Payment Method', :payment_method]]
      when :dwolla
        @breadcrumbs = [['Amount + Perks', :amount], ['Payment Method', :payment_method], ['Pay with Dwolla', :dwolla]]
        if current_member.linked_to_dwolla?
          @funding_sources = Dwolla::User.me(current_member.dwolla_auth_token).funding_sources.select{|f|
            f.verified
          }.map{|f|
            [f.name, f.id]
          }
          @funding_sources.unshift ['Dwolla Account', '']
        end
      when :cc
        @breadcrumbs = [['Amount + Perks', :amount], ['Payment Method', :payment_method], ['Pay with Credit Card', :cc]]
      end
    
      authorize! :edit, @pledge
      render_wizard
    end
  end
  
  def update
    authorize! :edit, @pledge
    if params[:pledge]
      @pledge.update_attributes params[:pledge]
    end
    if respond_to?("submit_#{step}")
      send "submit_#{step}"
    else
      render_wizard(@pledge)
    end
  end
  
  def submit_amount
    render_wizard(@pledge)
  end
  
  def submit_payment_method
    unless @pledge.valid?
      render_wizard(@pledge)
    else
      redirect_to wizard_path(@pledge.payment_method)
    end
  end
  
  def submit_cc
    begin
      token = params[:stripe_token]
      raise "blahblah" if token.blank?
      @charge = Stripe::Charge.create(
        :amount => @pledge.amount_cents, # amount in cents, again
        :currency => "usd",
        :card => token,
        :description => "CloudFunded pledge to #{@project.name}"
      )
      @stripe_transaction = StripeTransaction.from_stripe_charge(@charge)
      @stripe_transaction.member = current_member
      @stripe_transaction.pledge = @pledge
      @stripe_transaction.save!
      if @pledge.valid?
        @pledge.pay_by_cc!
      end
      render_wizard(@pledge)
    rescue Stripe::CardError => e
      flash[:alert] = e.message
      # puts e.inspect
      render :cc
    rescue Exception => e
      flash[:alert] = e.message
      # puts e.inspect
      render :cc
    end
  end
  
  def load_project
    @project = params[:project_id] ? 
                  Project.find(params[:project_id]) : 
                  current_member.project_application
    pledges = Pledge.where(project_id: @project.id, investor_id: current_member.id)
    @pledge = pledges.empty? ? pledges.create! : pledges.first
  end
  
  # def redirect_as_needed
  #   unless params[:id]
  #     if step != WORKFLOW_STATE_WIZARD_STEP[@pledge.workflow_state]
  #       the_correct_step = WORKFLOW_STATE_WIZARD_STEP[@pledge.workflow_state]
  #       if the_correct_step == :pledge
  #         redirect_to new_project_pledge_path(@project)
  #       else
  #         redirect_to new_project_pledge_path(@project, the_correct_step)
  #       end
  #     end
  #   end
  # end
  
  WORKFLOW_STATE_WIZARD_STEP = {
    'new' => :amount,
    'not_pledged' => :amount,
    'choose_payment_method' => :payment_method,
    'pay_by_cc' => :pay_by_cc,
    'payment_received' => :share
  }
end

app/controllers/projects/roles_controller.rb
class Projects::RolesController < ApplicationController
  respond_to :js
  before_filter :authenticate_member!, :load_project
  
  def new
    authorize! :edit, @project
    @role = @project.roles.build
    @role.invited_by = current_member
    respond_with @project, @role do |format|
      format.html {
        render layout: 'edit_projects'
      }
    end
  end
  
  def index
    authorize! :edit, @project
    @roles = @project.roles
    respond_with @project, @role do |format|
      format.html {
        render layout: 'edit_projects'
      }
    end
  end
  
  def create
    authorize! :edit, @project
    @role = @project.roles.build(params[:role])
    if @role.member
      @role.email_address = @role.member.email
    end
    @role.invited_by = current_member
    @member = Member.where(email: @role.email_address).first
    if @member
      @role.member = @member
    end
    @role.save
    respond_with @project, @role
  end
  
  def edit
    @role = @project.roles.find(params[:id])
    authorize! :edit, @role
    respond_with(@role,@project)
  end

  def update
    @role = @project.roles.find(params[:id])
    authorize! :edit, @role
    @role.update_attributes params[:role]
    respond_with(@role,@project)
  end
  
  def confirm
    @role = @project.roles.find(params[:id])
    authorize! :confirm, @role
    @role.confirm!
    respond_with @project, @role
  end
  
  def destroy
    @role = @project.roles.find(params[:id])
    authorize! :destroy, @role
    @role.destroy
    respond_with @project, @role
  end
  
  def load_project
    @project = Project.find(params[:project_id])
  end
end

app/controllers/projects/transactions_controller.rb
class Projects::TransactionsController < ApplicationController
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects/categories_helper.rb
module Projects::CategoriesHelper
end

app/helpers/projects/roles_helper.rb
module Projects::RolesHelper
end

app/views/projects/_dashboard.html.haml
.dashboard
  .row
    .span12.nomargin
      %h1.name= @project.name
      .ribbon
        %h2.tagline.shadow= @project.tagline
  .row
    .span8.white.shadow.nomargin 
      .titleinfo
      .dashboard_image_wrapper
        - if @project.youtube_url.present?
          %iframe{width: 560, height: 315, frameborder: 0, allowfullscreen: true, src: @project.youtube_url}
        - else
          = image_tag @project.image.url(:large), width: 'auto', height: 'auto'
      .social
        .social-links.align-center
          .link= like_button(@project)
          .link.pin-it= pinterest_tag(@project)
          .link= linkedin_tag(@project)
          .link= twitter_button(@project)
          .clear
    .span4.pixel20.nomargin
      .right-pane
        %h3.centered SUPPORT
        .fund_raising
          %h3.amount-raised= number_to_currency(@project.amount_pledged, precision: 0)
          .subtitle RAISED OF #{number_to_currency(@project.financial_goal, precision: 0)} GOAL
          = progress_bar(@project)
        .metrics
          .metric
            %span.large= @project.percent_complete.to_s + '%'
            %span.small Funded
          .metric
            %span.large= @project.pledges.paid.count
            %span.small Backers
          .metric
            %span.large= (@project.end_date - Date.today).to_i
            %span.small Days Left
          - if member_signed_in? && current_member.funded?(@project)
            = link_to project_my_pledge_path(@project) do
              .yellow.button1.large My Pledge
          - else
            = link_to new_project_pledge_path(@project), id: 'new_pledge' do
              .clear
              .btn.btn-large.btn-warning.cta Donate

app/views/projects/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = '<%= ENV['DISQUS_APPNAME'] %>';
    var disqus_developer = <%= ENV['DISQUS_DEVMODE'] || 0 %>;
    var disqus_identifier = '<%= project_path(@project) %>';
    var disqus_title = '<%= escape_javascript @project.name %> on CloudFunded';

</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/projects/_location_form.html.haml
.row
  .span3
    = f.control_group_text_field :address, label: 'Address, City or Zip', popover: { title: 'Address', content: 'Where are you?  Exact address, or city and state, even zip will do.', trigger: 'focus' }
  .span3
    #answer_wrapper
    .controls= button_tag 'Check Address', id: 'check_address', class: 'btn'
  
.row
  = f.hidden_field :lat
  = f.hidden_field :long
  = f.hidden_field :street_number
  = f.hidden_field :route
  = f.hidden_field :city
  = f.hidden_field :county
  = f.hidden_field :state
  = f.hidden_field :postal_code
  #map_canvas.span8

= content_for :head do
  = javascript_include_tag 'https://maps.googleapis.com/maps/api/js?sensor=false'

app/views/projects/_open_graph_data.html.haml
- unless @project.new_record?
  = content_for :open_graph do
    %link{rel: 'image_src', href: "http:#{@project.image.url(:original, true)}"}
    %meta{property: 'og:type', content: "#{AppConfig.opengraph_namespace}:campaign"}
    %meta{property: 'og:title', content: @project.name}
    %meta{property: 'og:image', content: "http:#{@project.image.url(:original, true)}"}
    %meta{property: 'og:description', content: @project.tagline}
    %meta#project_url{property: 'og:url', content: project_url(@project)}
    %meta{property: "#{AppConfig.opengraph_namespace}:financial_goal", content: number_to_currency(@project.financial_goal)}
    %meta{property: "#{AppConfig.opengraph_namespace}:amount_raised", content: number_to_currency(@project.amount_pledged)}
    %meta{property: "#{AppConfig.opengraph_namespace}:amount_remaining", content: number_to_currency(@project.amount_remaining)}
    -# = og_tag 'og:latitude', @project.lat
    -# = og_tag 'og:longitude', @project.long
    -# - if @project.route
    -#   = og_tag 'og:street-address', "#{@project.street_number} #{@project.route}"
    -# = og_tag 'og:locality', @project.city
    -# = og_tag 'og:postal-code', @project.postal_code
    -# = og_tag 'og:region', @project.state
    -# = og_tag 'og:country-name', 'USA'

app/views/projects/_project.html.haml
.span3.shadow[project]{data: {'project-path' => project_path(project), fb_post_id: project.fb_post_id}}
  .projecteaser= image_tag project.image.url(:medium), width: '300px'
  %h2= project.name
  .description= project.tagline
  -# .website_link= link_to project.website_url.shorten(36), project.website_url if project.website_url
  
  .progress-bar
    .progress.progress-success
      .bar{style: "width: #{project.percent_complete}%;"}
  %h3 #{number_to_currency(project.amount_pledged)} raised.  
  .btn #{link_to 'Learn More & Pledge', new_project_pledge_path(project)}

app/views/projects/_project_image_upload.html.haml
.field.upload_field{id: 'upload_image', data: {field: :image}}
  .upload_status Uploading...<br/><div class="progress progress-striped active"><div class="bar" style="width: 100%;"></div></div>
  - if @project.image.present?
    = image_tag @project.image.url(:large), alt: 'Project Image', id: 'image_tag'
  - else
    = image_tag 'projects/wizard/onebit_33.png', alt: 'Project Image', id: 'image_tag', class: 'hide'
  = image_tag 'projects/wizard/file_upload_placeholder.jpg', alt: 'Image Placeholder', id: 'image_placeholder_tag', class: "click_to_upload#{@project.image.present? ? ' hide' : ''}"
  = image_tag 'projects/wizard/change_file_placeholder.jpg', alt: 'Change Image', id: 'change_image_tag', class: "click_to_upload#{@project.image.present? ? '' : ' hide'}"
  .file_uploads{data: {action: project_path(@project, format: :json)}}
    = file_field_tag :image

app/views/projects/_project_info_field.html.haml
- if !@project.send(field).blank? || mercury_editor_open?
  %h1= title
  - if @project.send("#{field}_image").present?
    = image_tag @project.send("#{field}_image").url(:large)
  %div{mercury_full}(id=field)!= @project.send field

app/views/projects/_web_presence.html.haml
= form_for @project do |f|
  .field
    = f.label :google_places
    = f.text_field :google_places
  .field
    = f.label :facebook
    = f.text_field :facebook
  .field
    = f.label :linkedin_profile
    = f.text_field :linkedin_profile
  .field
    = f.label :linkedin_business
    = f.text_field :linkedin_business
  .field
    = f.label :yelp
    = f.text_field :yelp
  .field
    = f.label :google_plus
    = f.text_field :google_plus
  .field
    = f.submit

app/views/projects/index.html.haml
.row
  .span10.offset1= render @projects

app/views/projects/my_projects.html.haml
%h1 My Projects
%table.my_projects
  - @projects.each do |project|
    %tr.my_project
      %td.image
        = link_to project_path(project) do
          = image_tag project.image.url
      %td.details
        %h1= link_to project.name, project
        .status= "Status: #{project.workflow_state.titleize}"
        .links= link_to 'Edit Project', (project.live? ? edit_project_path(project) : project_wizard_path(project)) 
        .links= link_to 'Publish Updates, etc', '/editor/projects' + project_path(project)

app/views/projects/share.html.haml
.share_project.edit_project
  %h1 Awesome.  Get the word out.
  = form_for @project do |f|
    = f.check_box :post_to_fb
    = f.submit :next
    

app/views/projects/show.html.haml
.project_page
  - if can? :edit, @project
    = link_to edit_project_path(@project), class: 'edit_project_banner' do
      = image_tag 'projects/edit_my_project.png'
  = render partial: 'dashboard'
  .row
    .span8.details.blue1.mercury_container{data: {'save-url' => mercury_update_project_path(@project)}}
      #tab_container.btn-toolbar
        #tabs{data: {base_url: project_path(@project)}}
          .btn-group#tab-titles
            %a.btn.btn-info{active_tab?('info', true)}(href='#info' data-toggle='tab') Info
            %a.btn.btn-info{active_tab?('updates')}(href='#updates' data-toggle='tab') Updates
            %a.btn.btn-info{active_tab?('team')}(href='#team' data-toggle='tab') Team
            %a.btn.btn-info{active_tab?('comments')}(href='#comments' data-toggle='tab') Comments
            %a.btn.btn-info{active_tab?('pledges')}(href='#pledges' data-toggle='tab') Pledges
          .tab-content
            #info.tab-pane{active_tab?('info', true)}
              #information_text{mercury_full}!= @project.information_text
              %br/
              = render partial: 'project_info_field', locals: {field: 'about_your_product', title: 'About Our Company'}
              %br/
              = render partial: 'project_info_field', locals: {field: 'how_it_helps',       title: 'Our Contribution To The Community'}
              %br/
              = render partial: 'project_info_field', locals: {field: 'your_target_market', title: 'Our Target Market'}
              %br/
              = render partial: 'project_info_field', locals: {field: 'history',            title: 'Background'}

            #updates.tab-pane{active_tab?('updates')}
              - if mercury_editor_open?
                = link_to "New Update", project_updates_path(@project), method: :post
              = render partial: 'projects/articles/update', collection: @articles
            #team.tab-pane{active_tab?('team')}
              - if mercury_editor_open?
                = link_to "Add A Team Member", new_project_role_path(@project, format: :js), data: {remote: true}
              = render @roles
            #comments.tab-pane{active_tab?('comments')}
              = render partial: 'disqus'
            #pledges.tab-pane{active_tab?('pledges')}
              - @project.pledges.paid.each do |pledge|
                .pledge
                  = render pledge.investor
    #perks.perks.span4.nomargin.pixel10
      %h3.centered Donation Perks
      = render @project.perks
     

= render partial: 'shared/mercury_includes' if can? :edit, @project && mercury_editor_open?
= render partial: 'open_graph_data'